context:
  name: supabase-functions
  version: "0.10.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/supabase_functions/supabase_functions-${{ version }}.tar.gz
  sha256: 4779d33a1cc3d4aea567f586b16d8efdb7cddcd6b40ce367c5fb24288af3a4f1

build:
  number: 0
  noarch: python
  script: python -m pip install . -vv

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - poetry
  run:
    - python >=${{ python_min }}
    - httpx >=0.26,<0.29
    - strenum >=0.4.15,<0.5.0

tests:
  - python:
      imports:
      - supabase_functions
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  license: MIT
  license_file: LICENSE
  summary: Python client implementation for Supabase Functions
  homepage: https://github.com/supabase/functions-py
  repository: https://github.com/supabase/functions-py

extra:
  recipe-maintainers:
    - timkpaine
