context:
  name: supabase-functions
  version: "2.22.3"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/supabase_functions/supabase_functions-${{ version }}.tar.gz
  sha256: 65619acfacb032c935202b2f6430e54b63effb6b4e42e7b4368c61be40d9087b

build:
  number: 0
  noarch: python
  script: python -m pip install . -vv

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - uv-build >=0.8.3,<0.9.0
  run:
    - python >=${{ python_min }}
    - httpx >=0.26,<0.29
    - strenum >=0.4.15,<0.5.0
    - yarl >=1.20.1

tests:
  - python:
      imports:
        - supabase_functions
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  license: MIT
  license_file: LICENSE
  summary: Python client implementation for Supabase Functions
  homepage: https://github.com/supabase/supabase-py/tree/main/src/functions
  repository: https://github.com/supabase/supabase-py/tree/main/src/functions

extra:
  recipe-maintainers:
    - anand2312
    - J0
    - timkpaine
